"""create calendar table

Revision ID: 7578bf5c005a
Revises: a01bcf7b884c
Create Date: 2025-08-28 23:04:45.091378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7578bf5c005a"
down_revision: Union[str, None] = "a01bcf7b884c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_events",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("TASK", "MEETING", "OTHER", name="eventtype"),
            nullable=False,
        ),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_calendar_events_task_id_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_events")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_events")
    # ### end Alembic commands ###
