"""change types in comments table

Revision ID: a01bcf7b884c
Revises: 3e05d78bdbe3
Create Date: 2025-08-28 18:20:24.233832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a01bcf7b884c"
down_revision: Union[str, None] = "3e05d78bdbe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_comments",
        "author_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_comment="ID автора комментария из User Service (JWT token)",
        existing_nullable=False,
        postgresql_using="author_id::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_comments",
        "author_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_comment="ID автора комментария из User Service (JWT token)",
        existing_nullable=False,
        postgresql_using="author_id::text"
    )
    # ### end Alembic commands ###
