"""create tasks table

Revision ID: c7f7b15fe94f
Revises: 
Create Date: 2025-08-17 15:51:54.247561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7f7b15fe94f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "TODO", "IN_PROGRESS", "DONE", "CANCELLED", name="taskstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "creator_id",
            sa.String(),
            nullable=False,
            comment="ID юзера из User Service, кто назначает задачу",
        ),
        sa.Column(
            "assignee_id",
            sa.String(),
            nullable=False,
            comment="ID юзера из User Service, которому назначают задачу",
        ),
        sa.Column(
            "company_id",
            sa.String(),
            nullable=False,
            comment="ID компании из User Service",
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
