"""change types in tasks table

Revision ID: 3e05d78bdbe3
Revises: 9defbbd062e5
Create Date: 2025-08-28 17:22:46.061928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e05d78bdbe3"
down_revision: Union[str, None] = "9defbbd062e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "creator_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_comment="ID юзера из User Service, кто назначает задачу",
        existing_nullable=False,
        postgresql_using='creator_id::integer'
    )
    op.alter_column(
        "tasks",
        "assignee_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_comment="ID юзера из User Service, которому назначают задачу",
        existing_nullable=False,
        postgresql_using='assignee_id::integer'
    )
    op.alter_column(
        "tasks",
        "company_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_comment="ID компании из User Service",
        existing_nullable=False,
        postgresql_using='company_id::integer'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "company_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_comment="ID компании из User Service",
        existing_nullable=False,
        postgresql_using='company_id::text'
    )
    op.alter_column(
        "tasks",
        "assignee_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_comment="ID юзера из User Service, которому назначают задачу",
        existing_nullable=False,
        postgresql_using='assignee_id::text'
    )
    op.alter_column(
        "tasks",
        "creator_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_comment="ID юзера из User Service, кто назначает задачу",
        existing_nullable=False,
        postgresql_using='creator_id::text'
    )
    # ### end Alembic commands ###