"""create comments table

Revision ID: 9defbbd062e5
Revises: c7f7b15fe94f
Create Date: 2025-08-28 14:19:11.493249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9defbbd062e5"
down_revision: Union[str, None] = "c7f7b15fe94f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_comments",
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "task_id",
            sa.Integer(),
            nullable=False,
            comment="ID задачи, к которой относится комментарий",
        ),
        sa.Column(
            "author_id",
            sa.String(),
            nullable=False,
            comment="ID автора комментария из User Service (JWT token)",
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_comments_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_comments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_comments")
    # ### end Alembic commands ###
